-- ==============================================================================
-- SCHEMA SUPABASE - BetTracker Pro
-- ==============================================================================
-- Ejecuta este script en el Editor SQL de tu proyecto Supabase Dashboard.

-- 1. Habilitar extensión UUID (si no está activa)
create extension if not exists "uuid-ossp";

-- 2. Tabla de Usuarios de la App (Perfiles y Estado de Membresía)
-- Se vincula con auth.users
create table if not exists public.app_users (
  user_id uuid references auth.users(id) on delete cascade primary key,
  email text,
  membership_tier text default 'FREE' check (membership_tier in ('FREE', 'PRO')),
  membership_duration text default 'MONTHLY' check (membership_duration in ('MONTHLY', 'YEARLY', 'LIFETIME')),
  membership_expires_at timestamptz,
  created_at timestamptz default now()
);

-- RLS para app_users
alter table public.app_users enable row level security;
create policy "Usuarios pueden ver su propio perfil" on public.app_users for select using (auth.uid() = user_id);
-- Permitimos update por si queremos que el usuario edite datos basicos
create policy "Usuarios pueden actualizar su propio perfil" on public.app_users for update using (auth.uid() = user_id);

-- Trigger para crear perfil automáticamente al registrarse
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.app_users (user_id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Borrar trigger si existe para recrearlo
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 3. Estado de Apuestas (Persistencia del Dashboard principal)
create table if not exists public.betting_state (
  user_id uuid references auth.users(id) on delete cascade primary key,
  config jsonb,
  plan jsonb,
  current_balance numeric,
  theme text default 'light',
  updated_at timestamptz default now()
);

-- RLS para betting_state
alter table public.betting_state enable row level security;
create policy "Usuarios ven su propio estado" on public.betting_state for select using (auth.uid() = user_id);
create policy "Usuarios pueden crear/modificar su propio estado" on public.betting_state for all 
  using (auth.uid() = user_id) 
  with check (auth.uid() = user_id);


-- 4. Planes Guardados (Múltiples planes por usuario)
create table if not exists public.saved_plans (
  id text primary key, -- Usamos text porque el ID puede venir del cliente
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  config jsonb not null,
  plan jsonb not null,
  saved_at timestamptz default now()
);

-- RLS para saved_plans
alter table public.saved_plans enable row level security;
create policy "Usuarios ven sus planes guardados" on public.saved_plans for select using (auth.uid() = user_id);
create policy "Usuarios gestionan sus planes guardados" on public.saved_plans for all 
  using (auth.uid() = user_id) 
  with check (auth.uid() = user_id);


-- 5. Configuración de Límites de Planes (Sistema Admin)
create table if not exists public.plan_settings (
  id int primary key generated by default as identity,
  free_max_saved_plans int default 2,
  pro_max_saved_plans int default 10
);

-- Insertar configuración por defecto
insert into public.plan_settings (id, free_max_saved_plans, pro_max_saved_plans)
values (1, 2, 10)
on conflict (id) do nothing;

-- RLS plan_settings (Lectura pública autenticada)
alter table public.plan_settings enable row level security;
create policy "Lectura de settings de planes" on public.plan_settings for select using (true);


-- 6. Logros (Achievements) - Gestión Admin
create table if not exists public.achievements (
  id uuid default uuid_generate_v4() primary key,
  parley_name text not null,
  line text not null,
  momio text not null,
  description text,
  result text check (result in ('PENDING', 'HIT', 'MISS')) default 'PENDING',
  created_at timestamptz default now()
);

-- RLS achievements
alter table public.achievements enable row level security;
create policy "Lectura de logros autenticada" on public.achievements for select using (auth.role() = 'authenticated');


-- 7. Likes de Logros (Interacción Social)
create table if not exists public.achievement_likes (
  achievement_id uuid references public.achievements(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  primary key (achievement_id, user_id)
);

-- RLS likes
alter table public.achievement_likes enable row level security;
create policy "Usuarios ven todos los likes" on public.achievement_likes for select using (true);
create policy "Usuarios dan like propio" on public.achievement_likes for insert with check (auth.uid() = user_id);
create policy "Usuarios quitan like propio" on public.achievement_likes for delete using (auth.uid() = user_id);


-- 8. Configuración de Logros (Límites diarios de visualización)
create table if not exists public.achievement_settings (
  id int primary key generated by default as identity,
  free_daily_limit int default 1,
  pro_daily_limit int default 5
);

insert into public.achievement_settings (id, free_daily_limit, pro_daily_limit)
values (1, 1, 5)
on conflict (id) do nothing;

alter table public.achievement_settings enable row level security;
create policy "Lectura settings logros" on public.achievement_settings for select using (true);
